"""initial

Revision ID: 409723898b7d
Revises: None
Create Date: 2017-01-04 21:22:48.901839

"""

# revision identifiers, used by Alembic.
revision = '409723898b7d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
